/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frequenzkennlinienmessung.gui;
import Frequenzkennlinienmessung.Fluke45V2019;
import Frequenzkennlinienmessung.WG810V2019;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import Frequenzkennlinienmessung.data.MeasureValue;
import Frequenzkennlinienmessung.data.Waveform;
import Frequenzkennlinienmessung.gui.MeasuredValuesListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author nicob
 */
public class MessGUI extends javax.swing.JFrame {

    private final List<MeasureValue> measureValesList = new ArrayList<>();

    public MessGUI() {
        initComponents();
        UpdateModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        WaveformGroup = new javax.swing.ButtonGroup();
        pMain = new javax.swing.JPanel();
        pSide = new javax.swing.JPanel();
        pKurvenform = new javax.swing.JPanel();
        raDreieck = new javax.swing.JRadioButton();
        raRechteck = new javax.swing.JRadioButton();
        raSinus = new javax.swing.JRadioButton();
        pBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        tfAmplitude = new javax.swing.JFormattedTextField();
        tfFrequenz = new javax.swing.JFormattedTextField();
        pCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LData = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMain.setLayout(new java.awt.BorderLayout());

        pSide.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("WG810")));
        pSide.setLayout(new java.awt.BorderLayout());

        pKurvenform.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder("Kurvenform")));
        pKurvenform.setPreferredSize(new java.awt.Dimension(124, 162));
        pKurvenform.setLayout(new java.awt.GridLayout(0, 1));

        WaveformGroup.add(raDreieck);
        raDreieck.setSelected(true);
        raDreieck.setText("Dreieck");
        pKurvenform.add(raDreieck);

        WaveformGroup.add(raRechteck);
        raRechteck.setText("Rechteck");
        pKurvenform.add(raRechteck);

        WaveformGroup.add(raSinus);
        raSinus.setText("Sinus");
        pKurvenform.add(raSinus);

        pSide.add(pKurvenform, java.awt.BorderLayout.NORTH);

        pBottom.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Amplitude");
        pBottom.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Frequenz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pBottom.add(jLabel2, gridBagConstraints);

        jLabel3.setText("V");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pBottom.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Hz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        pBottom.add(jLabel4, gridBagConstraints);

        jButton4.setText("WG810 einstellen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnSetWG810(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pBottom.add(jButton4, gridBagConstraints);

        tfAmplitude.setColumns(18);
        tfAmplitude.setValue(0.0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pBottom.add(tfAmplitude, gridBagConstraints);

        tfFrequenz.setColumns(18);
        tfFrequenz.setValue(0.0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pBottom.add(tfFrequenz, gridBagConstraints);

        pSide.add(pBottom, java.awt.BorderLayout.CENTER);

        pMain.add(pSide, java.awt.BorderLayout.LINE_START);

        pCenter.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Fluke45")));
        pCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(LData);

        pCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("einlesen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnReadData(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("löschen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnDeletData(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("speichern");
        jPanel2.add(jButton3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCenter.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pMain.add(pCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnSetWG810(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnSetWG810
        
        try(WG810V2019 wg810 = new WG810V2019("COM11"))
        {
            wg810.setRemote(true);
            wg810.setAmplitude(((Number)tfAmplitude.getValue()).doubleValue(), true);
            wg810.setFrequenz(((Number)tfFrequenz.getValue()).doubleValue(), true);
            
            switch (getRadioButtonValues()) {
                case TRIANGLE -> wg810.setKurvenform(WG810V2019.FORMTRI, 0, true);
                case RECTANGLE -> wg810.setKurvenform(WG810V2019.FORMRECT, 0, true);
                case SINE -> wg810.setKurvenform(WG810V2019.FORMSIN, 0, true);
                default -> throw new AssertionError();
}

            
            wg810.setRemote(false);
            
        } catch (Exception ex) {
            Logger.getLogger(MessGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OnSetWG810

    private void OnReadData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnReadData
        double ua = 0;
        try(Fluke45V2019 mg1 = new Fluke45V2019("COM10"))
        {         
            ua = mg1.getValue();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        measureValesList.add(new MeasureValue(getRadioButtonValues(),
                ((Number)tfFrequenz.getValue()).doubleValue(),
                ((Number)tfAmplitude.getValue()).doubleValue(),
                ua));
        
        UpdateModel();
    }//GEN-LAST:event_OnReadData

    private void OnDeletData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnDeletData
        LData.setModel(new MeasuredValuesListModel(new ArrayList<>()));
    }//GEN-LAST:event_OnDeletData
    
    private void UpdateModel(){
        LData.setModel(new MeasuredValuesListModel(measureValesList));
    }
    
    private Waveform getRadioButtonValues(){
        if(raDreieck.isSelected())
            return Waveform.TRIANGLE;
        
        if(raRechteck.isSelected())
            return Waveform.RECTANGLE;
        
        if(raSinus.isSelected())
            return Waveform.SINE;
        
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<MeasureValue> LData;
    private javax.swing.ButtonGroup WaveformGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBottom;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pKurvenform;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSide;
    private javax.swing.JRadioButton raDreieck;
    private javax.swing.JRadioButton raRechteck;
    private javax.swing.JRadioButton raSinus;
    private javax.swing.JFormattedTextField tfAmplitude;
    private javax.swing.JFormattedTextField tfFrequenz;
    // End of variables declaration//GEN-END:variables
}
